import { useEffect, useMemo, useState } from "react";
import { NavLink, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { games } from "./data/games";

const isDesktop = import.meta.env.VITE_PCForge_DESKTOP === "true";

function PlaceholderPage({title,description}) {
  return <main className="page-shell"><section className="placeholder"><span className="eyebrow">PCForge</span><h1>{title}</h1><p>{description}</p></section></main>;
}

function Home(){return <main><section className="hero page-shell"><div><span className="eyebrow">PC compatibility, simplified</span><h1>Can your PC<br/><span>run it?</span></h1><p className="hero-text">PCForge scans your Windows hardware and turns confusing game requirements into a clear compatibility check.</p><div className="hero-actions"><NavLink className="button button-primary" to="/my-pc">Check my PC</NavLink><NavLink className="button button-secondary" to="/games">Browse games</NavLink></div><div className="trust-row"><span>Local hardware scan</span><span>•</span><span>No personal files read</span><span>•</span><span>Windows desktop app</span></div></div><div className="hero-panel"><div className="panel-top"><span className="status-dot"/><span>PCForge Scanner</span><span className="panel-state">Ready</span></div><div className="scan-visual"><div className="scan-ring"><span>PC</span></div><div><strong>Know your hardware.</strong><p>CPU, GPU, RAM, storage and display information in one scan.</p></div></div><div className="spec-preview"><div><small>CPU</small><strong>Detected locally</strong></div><div><small>GPU</small><strong>Detected locally</strong></div><div><small>RAM</small><strong>Detected locally</strong></div></div><div className="scan-line"><span/></div><p>Desktop scanning runs on your machine. The web version can download the desktop scanner.</p></div></section><section className="section page-shell"><div className="section-heading"><span className="eyebrow">How it works</span><h2>Three steps.<br/><span>One answer.</span></h2></div><div className="steps-grid"><article className="step-card"><span>01</span><h3>Scan</h3><p>PCForge reads the hardware Windows exposes locally.</p></article><article className="step-card"><span>02</span><h3>Choose a game</h3><p>Browse the library and open the game's minimum and recommended requirements.</p></article><article className="step-card"><span>03</span><h3>Get a verdict</h3><p>Compare your detected system with the listed requirements.</p></article></div></section><section className="privacy-section page-shell"><div><span className="eyebrow">Privacy by design</span><h2>Your hardware.<br/><span>Your machine.</span></h2></div><p>PCForge is designed around local hardware detection. The scanner does not need your documents, passwords, browser history, cookies or personal files.</p></section><section className="cta-section page-shell"><span className="eyebrow">Ready?</span><h2>Find out what<br/>your PC can run.</h2><NavLink className="button button-primary" to="/my-pc">Open PC Scanner</NavLink></section></main>;}
function About() {
 return <main className="about-page page-shell">
  <section className="about-hero"><span className="eyebrow">About PCForge</span><h1>PC requirements<br/><span>without the headache.</span></h1><p>PCForge turns confusing hardware requirements into a simple answer: can your PC run the game you want to play?</p><NavLink className="button button-primary" to="/my-pc">Check my PC</NavLink></section>
  <section className="about-grid">
   <article><span>01</span><h2>Hardware first.</h2><p>PCForge focuses on the components that actually affect whether a game can run: CPU, GPU, RAM, storage and system details.</p></article>
   <article><span>02</span><h2>Private by design.</h2><p>Your machine is not a permanent hardware profile. PCForge is designed around local compatibility checks.</p></article>
   <article><span>03</span><h2>Built for clarity.</h2><p>Instead of a wall of specifications, PCForge turns comparisons into straightforward verdicts you can understand.</p></article>
  </section>
 </main>;
}

const navItems=[{label:"Overview",to:"/"},{label:"Games",to:"/games"},{label:"My PC",to:"/my-pc"},{label:"Drivers",to:"/drivers"},{label:"Settings",to:"/settings"}];

function DesktopSidebar() {
 return <aside className="desktop-sidebar">
  <NavLink className="desktop-brand" to="/"><span className="brand-mark">P</span><span>PCForge</span></NavLink>
  <div className="sidebar-section">
   <span className="sidebar-label">WORKSPACE</span>
   <nav>{navItems.map(item=><NavLink key={item.to} to={item.to} end={item.to==="/"} className="sidebar-link"><span className="sidebar-icon">{item.label==="Overview"?"⌂":item.label==="Games"?"□":item.label==="My PC"?"▣":item.label==="Drivers"?"↻":"⚙"}</span><span>{item.label}</span></NavLink>)}</nav>
  </div>
  <div className="sidebar-bottom"><div className="desktop-status"><span className="status-dot online"/><span><strong>PCForge Desktop</strong><small>Ready</small></span></div><span className="sidebar-version">v1.0.0</span></div>
 </aside>;
}

function DesktopTopbar() {
 return <header className="desktop-topbar"><div><span className="eyebrow">PCForge Desktop</span><strong>PC compatibility, simplified.</strong></div><NavLink className="topbar-scan" to="/my-pc">Scan my PC <span>→</span></NavLink></header>;
}

function Games() {
 const [query,setQuery]=useState(""); const navigate=useNavigate();
 const filtered=useMemo(()=>games.filter(game=>`${game.title} ${game.genre} ${game.platform}`.toLowerCase().includes(query.trim().toLowerCase())),[query]);
 return <main className="games-page page-shell">
  <section className="games-hero"><div><span className="eyebrow">Game library</span><h1>Find a game<br/><span>to check.</span></h1><p>Browse the PCForge library and compare a game's requirements against your hardware.</p></div><label className="game-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search games..." aria-label="Search games"/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear search">×</button>}</label></section>
  <section className="games-results"><div className="results-heading"><div><span className="eyebrow">Library</span><h2>{filtered.length} {filtered.length===1?"game":"games"}</h2></div><span className="results-hint">More titles will be added from the live catalog.</span></div>
   {filtered.length?<div className="games-grid">{filtered.map(game=><article className="game-card" key={game.id} onClick={()=>navigate(`/games/${game.id}`)} tabIndex="0" role="button" onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&navigate(`/games/${game.id}`)}><div className="game-art"><span>{game.title.slice(0,1)}</span><small>PCForge</small></div><div className="game-card-body"><div className="game-meta"><span>{game.genre}</span><span>{game.platform}</span></div><h3>{game.title}</h3><p>{game.requirements}</p><span className="game-link">View requirements <b>→</b></span></div></article>)}</div>:<div className="empty-games"><span>⌕</span><h3>No games found</h3><p>Try a different title, genre, or platform.</p><button className="button button-secondary" onClick={()=>setQuery("")}>Clear search</button></div>}
  </section>
 </main>;
}

function MyPC() {
 const [status,setStatus]=useState("idle"); const [specs,setSpecs]=useState(null); const [error,setError]=useState("");
 useEffect(()=>{try{const saved=localStorage.getItem("pcforge_scan");if(saved)setSpecs(JSON.parse(saved));}catch{}},[]);
 const scan=async()=>{if(!isDesktop||!window.pcforge?.scanSystem)return;setStatus("scanning");setError("");const result=await window.pcforge.scanSystem();if(!result.ok){setStatus("error");setError(result.error||"Hardware scan failed.");return;}setSpecs(result.data);setStatus("ready");localStorage.setItem("pcforge_scan",JSON.stringify(result.data));};
 const cpu=specs?.cpu,gpu=specs?.gpus?.[0],ram=specs?.memory,disk=specs?.storage?.[0],display=specs?.display?.modes?.find(m=>m.width&&m.height);
 const values=[
  ["CPU",cpu?.name||"Not detected",cpu?(String(cpu.cores||"?")+" cores · "+String(cpu.threads||"?")+" threads"):"Waiting for scan"],
  ["GPU",gpu?.name||"Not detected",gpu?.driverVersion?("Driver "+gpu.driverVersion):"Waiting for scan"],
  ["RAM",ram?.totalGB?(ram.totalGB+" GB"):"Not detected",ram?(String(ram.modules?.length||0)+" module"+((ram.modules?.length||0)===1?"":"s")):"Waiting for scan"],
  ["Storage",disk?.totalGB?(disk.freeGB+" GB free"):"Not detected",disk?(disk.totalGB+" GB total · "+disk.drive):"Waiting for scan"],
  ["Windows",specs?.os?.name||"Not detected",specs?.os?.build?("Build "+specs.os.build):"Waiting for scan"],
  ["Display",display?((display.width||0)+" × "+(display.height||0)):"Not detected",display?.refreshRate?(display.refreshRate+" Hz"):"Waiting for scan"],
  ["Motherboard",specs?.motherboard?.model||"Not detected",specs?.motherboard?.manufacturer||"Waiting for scan"],
  ["Security",specs?.security?.tpm?.Present?"TPM present":"Not detected",specs?.security?.secureBoot===true?"Secure Boot on":specs?.security?.secureBoot===false?"Secure Boot off":"Secure Boot unavailable"]
 ];
 return <main className="pc-page page-shell"><section className="pc-hero"><div><span className="eyebrow">Your hardware</span><h1>Know your<br/><span>PC.</span></h1><p>PCForge reads gaming-relevant hardware directly from Windows. Nothing is uploaded to a server.</p>{isDesktop?<button className="button button-primary" onClick={scan} disabled={status==="scanning"}>{status==="scanning"?"Scanning…":"Scan my PC"}</button>:<a className="button button-primary" href="https://github.com/adiyandev/PCForge/releases/latest">Download PCForge</a>}{error&&<p className="scan-error">{error}</p>}</div><div className={"pc-status-card "+status}><span className={"status-dot "+(status==="ready"?"online":"")}/><span>{status==="ready"?"Scanner complete":status==="scanning"?"Scanning system":status==="error"?"Scan failed":"Scanner ready"}</span><strong>{status==="ready"?"Hardware profile ready":status==="scanning"?"Checking Windows hardware":status==="error"?"Could not read the system":"Ready when you are"}</strong><small>{status==="ready"?"Detected locally by PCForge.":status==="scanning"?"Reading CPU, graphics, memory, storage and system information.":status==="error"?error:"No hardware data has been collected yet."}</small></div></section><section className="hardware-section"><div className="section-heading"><span className="eyebrow">Hardware profile</span><h2>Your gaming<br/><span>specs.</span></h2></div><div className="hardware-grid">{values.map(([label,value,sub])=><article className={"hardware-card "+(!specs?"pending":"")} key={label}><small>{label}</small><strong>{value}</strong><span>{sub}</span></article>)}</div></section><section className="scan-privacy"><div><span className="eyebrow">Privacy</span><h2>Hardware only.<br/><span>Nothing personal.</span></h2></div><p>The desktop scanner reads hardware and Windows configuration through local system APIs. It does not need documents, passwords, browser history, cookies, or personal files.</p></section></main>;
}
function getCompatibility(game,scan){const r=game.requirementsData;const ram=Number(scan.memory?.totalGB||0);const free=Number(scan.storage?.reduce((a,d)=>a+Number(d.freeGB||0),0)||0);const ramMin=Number.parseInt(r.ram)||0;const ramRec=Number.parseInt(r.recommended.ram)||ramMin;const ramOk=ram>=ramMin,ramRecOk=ram>=ramRec;const storageMin=Number.parseInt(r.storage)||0;const storageOk=free>=storageMin;const cpuText=(scan.cpu?.name||"").toLowerCase();const gpuText=(scan.gpus?.map(g=>g.name).join(" ")||"").toLowerCase();const cpuMin=r.cpu.toLowerCase().split("/")[0].trim().split(" ").filter(x=>x.length>2).slice(-1)[0];const gpuMin=r.gpu.toLowerCase().split("/")[0].trim().split(" ").filter(x=>x.length>2).slice(-1)[0];const cpuMatch=cpuMin&&cpuText.includes(cpuMin);const gpuMatch=gpuMin&&gpuText.includes(gpuMin);if(ramOk&&storageOk&&(cpuMatch||gpuMatch))return ramRecOk&&cpuMatch&&gpuMatch?{title:"Recommended",reason:"Your detected hardware meets the listed recommended checks.",icon:"✓",className:"good"}:{title:"Playable",reason:"Your PC passes the available minimum checks, but some components may need lower settings.",icon:"✓",className:"good"};if(ramOk&&storageOk)return{title:"Likely playable",reason:"Memory and storage are sufficient; CPU/GPU model matching is conservative.",icon:"~",className:"maybe"};return{title:"Below minimum",reason:"Your detected system does not meet one or more listed minimum checks.",icon:"!",className:"bad"};}

function GameDetails() {
 const {gameId}=useParams(); const game=games.find(item=>item.id===gameId); const [scan,setScan]=useState(null);
 useEffect(()=>{try{const saved=localStorage.getItem("pcforge_scan");if(saved)setScan(JSON.parse(saved));}catch{}},[]);
 if(!game)return <PlaceholderPage title="Game not found." description="That game is not in the PCForge library yet." />;
 const r=game.requirementsData;
 const verdict=scan?getCompatibility(game,scan):null;
 const rows=[["CPU",r.cpu,r.recommended.cpu],["GPU",r.gpu,r.recommended.gpu],["RAM",r.ram,r.recommended.ram],["Storage",r.storage,r.recommended.storage]];
 return <main className="details-page page-shell"><section className="details-hero"><div><span className="eyebrow">Compatibility check</span><h1>Can you run<br/><span>{game.title}?</span></h1><p>Compare this game's requirements with your detected PC hardware.</p></div><div className={"verdict-card "+(verdict?.className||"")}><span className="verdict-icon">{verdict?.icon||"?"}</span><span className="eyebrow">Your verdict</span><strong>{verdict?.title||"Waiting for PC scan"}</strong><p>{verdict?.reason||"Run a local scan to compare your hardware."}</p><NavLink className="button button-primary" to="/my-pc">{verdict?"View My PC":"Scan my PC"}</NavLink></div></section><section className="requirements-section"><div className="requirements-heading"><div><span className="eyebrow">System requirements</span><h2>What {game.title} needs.</h2></div><span className="requirement-note">{game.genre} · {game.platform}</span></div><div className="requirement-table"><div className="req-row req-head"><span>Component</span><span>Minimum</span><span>Recommended</span></div>{rows.map(([label,min,max])=><div className="req-row" key={label}><strong>{label}</strong><span>{min}</span><span>{max||"Not specified"}</span></div>)}</div></section></main>;
}
function Dashboard(){const [scanned,setScanned]=useState(false);useEffect(()=>setScanned(!!localStorage.getItem("pcforge_scan")),[]);return <main className="dashboard page-shell"><section className="dashboard-hero"><div><span className="eyebrow">Overview</span><h1>Everything you need<br/><span>to check your PC.</span></h1><p>Scan your hardware, browse games, and get a clear compatibility verdict.</p><div className="dashboard-actions"><NavLink className="button button-primary" to="/my-pc">{scanned?"Rescan my PC":"Scan my PC"}</NavLink><NavLink className="button button-secondary" to="/games">Browse games</NavLink></div></div><div className="dashboard-card"><div className="card-heading"><span>System status</span><span className="status-badge"><i/> {scanned?"Scanned":"Ready"}</span></div><div className="dashboard-stat"><strong>{scanned?"Hardware detected":"Not scanned"}</strong><span>{scanned?"Local profile available for compatibility checks":"Run your first PCForge scan"}</span></div><div className="dashboard-divider"/><div className="dashboard-mini"><span>Hardware detection</span><b>{scanned?"Complete":"Ready"}</b></div><div className="dashboard-mini"><span>Game library</span><b>{games.length} titles</b></div></div></section><section className="dashboard-grid"><article><span className="eyebrow">My PC</span><h2>See what your machine is made of.</h2><p>CPU, GPU, memory, storage, Windows and display information in one place.</p><NavLink to="/my-pc">Open My PC →</NavLink></article><article><span className="eyebrow">Games</span><h2>Check before you install.</h2><p>Open a game and see its minimum and recommended requirements.</p><NavLink to="/games">Browse library →</NavLink></article></section></main>;}

function Drivers(){const [scan,setScan]=useState(null);useEffect(()=>{try{const s=localStorage.getItem("pcforge_scan");if(s)setScan(JSON.parse(s));}catch{}},[]);const drivers=scan?.gpus||[];return <main className="page-shell simple-page"><span className="eyebrow">System drivers</span><h1>Drivers.</h1><p>PCForge reports the driver versions Windows exposes locally. It does not claim that a driver is outdated without a trustworthy version source.</p>{drivers.length?<div className="driver-list">{drivers.map((d,i)=><article className="coming-card" key={i}><span>Graphics adapter</span><strong>{d.name}</strong><small>{d.driverVersion?"Driver "+d.driverVersion:"Driver version unavailable"}{d.driverDate?" · "+d.driverDate:""}</small></article>)}</div>:<div className="coming-card"><span>No scan yet</span><strong>Run a PC scan to see installed graphics driver information.</strong></div>}</main>;}
function Settings(){const clear=()=>{localStorage.removeItem("pcforge_scan");location.reload();};return <main className="page-shell simple-page"><span className="eyebrow">Preferences</span><h1>Settings.</h1><p>PCForge keeps the latest hardware profile locally so game checks work without scanning every time.</p><div className="coming-card"><span>Local data</span><strong>Your saved hardware profile stays in this app.</strong><button className="button button-secondary" onClick={clear}>Clear hardware profile</button></div></main>;}

function App() {
 const content=<Routes><Route path="/" element={isDesktop?<Dashboard/>:<Home/>}/><Route path="/games" element={<Games/>}/><Route path="/games/:gameId" element={<GameDetails/>}/><Route path="/my-pc" element={<MyPC/>}/><Route path="/about" element={<About/>}/><Route path="/drivers" element={<Drivers/>}/><Route path="/settings" element={<Settings/>}/></Routes>;
 if(!isDesktop)return <div className="app"><header className="site-header"><NavLink className="brand" to="/"><span className="brand-mark">P</span><span>PCForge</span></NavLink><nav className="nav-links">{[{label:"Home",to:"/"},{label:"Games",to:"/games"},{label:"My PC",to:"/my-pc"},{label:"About",to:"/about"}].map(item=><NavLink key={item.to} to={item.to} className="nav-link">{item.label}</NavLink>)}</nav><NavLink className="header-cta" to="/my-pc">Open Scanner</NavLink></header>{content}<footer className="site-footer page-shell"><span>PCForge</span><span>Can Your PC Run It?</span></footer></div>;
 return <div className="desktop-app"><DesktopSidebar/><div className="desktop-main"><DesktopTopbar/>{content}</div></div>;
}
export default App;
